### PR TITLE
Update from View.propTypes to ViewPropTypes to match RN v0.44.0

### PR DESCRIPTION
**Pull request by TBouder**
Update the ViewPropTypes to match the last revision of React Native V0.44.0

> View.propTypes to ViewPropTypes (53905a5) - @bvaughn

https://github.com/facebook/react-native/releases

### CODE REVIEW

**Comment by gusgard** [comment]
+1

**Comment by jhalborg** [comment]
Can someone please merge this in so we can get rid of this bloody warning? :) https://github.com/react-community/react-navigation/issues/1352

**Comment by samanthacampisi** [comment]
Please merge this. It's not a big change but it's necessary.

**Comment by adriaferre** [comment]
Please merge!

**Comment by breogangf** [comment]
You should merge this guys

**Comment by adrienthiery** [comment]
@leecade : Anything we can do to help merging this?

**Comment by bang88** [comment]
I switch to the latest RN this morning ,seems its an error now, so this definitely needs to repair.

**Comment by jhalborg** [comment]
@leecade @leecades - Can you, or one of your friends who help maintain this great library, please have a look at this pull request soon? Thanks

**Comment by fungilation** [comment]
A bit strange that I didn't see warnings at RN 0.44, but they are showing now after upgrade to RN 0.45?

console:
```
Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
reactConsoleErrorHandler	@	ExceptionsManager.js:71
printWarning	@	warning.js:36
warning	@	warning.js:60
get	@	react.development.js:2133
(anonymous)	@	index.js:101
loadModuleImplementation	@	require.js:174
guardedLoadModule	@	require.js:126
_require	@	require.js:110
(anonymous)	@	index.js:1
loadModuleImplementation	@	require.js:174
guardedLoadModule	@	require.js:126
_require	@	require.js:110
(anonymous)	@	components.js:28
loadModuleImplementation	@	require.js:174
guardedLoadModule	@	require.js:126
_require	@	require.js:110
(anonymous)	@	index.ios.js:85
loadModuleImplementation	@	require.js:174
guardedLoadModule	@	require.js:119
_require	@	require.js:110
(anonymous)	@	redux-logger.js:1
executeApplicationScript	@	debuggerWorker.js:40
(anonymous)	@	debuggerWorker.js:65

18:29:38.112 ExceptionsManager.js:71 Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
reactConsoleErrorHandler @ ExceptionsManager.js:71
printWarning @ warning.js:36
warning @ warning.js:60
get @ react.development.js:2125
(anonymous) @ View.js:84
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
get View @ react-native-implementation.js:56
(anonymous) @ index.js:103
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ index.js:1
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ components.js:28
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ index.ios.js:85
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:119
_require @ require.js:110
(anonymous) @ redux-logger.js:1
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:65

18:29:38.116 ExceptionsManager.js:71 Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
reactConsoleErrorHandler @ ExceptionsManager.js:71
printWarning @ warning.js:36
warning @ warning.js:60
get @ View.js:185
(anonymous) @ index.js:103
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ index.js:1
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ components.js:28
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ index.ios.js:85
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:119
_require @ require.js:110
(anonymous) @ redux-logger.js:1
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:65
18:29:38.429 

Warning: checkPropTypes has been moved to a separate package. Accessing React.checkPropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
reactConsoleErrorHandler	@	ExceptionsManager.js:71
console.error	@	YellowBox.js:67
printWarning	@	warning.js:36
warning	@	warning.js:60
get	@	react.development.js:2117
(anonymous)	@	index.ios.bundle?platform=ios&dev=true&minify=false:38714
loadModuleImplementation	@	require.js:174
guardedLoadModule	@	require.js:119
_require	@	require.js:110
get LayoutAnimation	@	react-native-implementation.js:83
checkClipboard$	@	components.js:1213
tryCatch	@	runtime.js:63
invoke	@	runtime.js:337
prototype.(anonymous function)	@	runtime.js:96
tryCatch	@	runtime.js:63
invoke	@	runtime.js:139
(anonymous)	@	runtime.js:147
tryCallOne	@	core.js:37
(anonymous)	@	core.js:123
(anonymous)	@	JSTimers.js:117
callTimer	@	JSTimersExecution.js:95
callImmediatesPass	@	JSTimersExecution.js:199
callImmediates	@	JSTimersExecution.js:214
(anonymous)	@	MessageQueue.js:223
__guard	@	MessageQueue.js:213
__callImmediates	@	MessageQueue.js:223
(anonymous)	@	MessageQueue.js:121
__guard	@	MessageQueue.js:213
invokeCallbackAndReturnFlushedQueue	@	MessageQueue.js:119
(anonymous)	@	debuggerWorker.js:71
```

The first 3 warnings all trace at `(anonymous)	@	components.js:28`, with line:
`import Swiper from 'react-native-swiper'`

**Comment by sabbyt** [comment]
+1

**Comment by jhalborg** [comment]
What seems to be the officer, problem? :) The merge seems to have been approved over two weeks ago now?

**Comment by adrienthiery** [comment]
Ping @samanthacampisi @breogangf ? Do you have the rights to merge ?

**Comment by zachrnolan** [comment]
Would love to see this merged! Is this project still being maintained?

**Comment by mackenzie-gray** [comment]
+1 to get this merged!

**Comment by fungilation** [comment]
@leecade, at least a heads up if you don't have time to maintain this?

**Comment by LostCrew** [comment]
Please, merge!

**Comment by bvaughn** [comment]
There's a lot of comments asking for merge. Why keep adding duplicates? This project is [MIT](https://github.com/leecade/react-native-swiper/blob/master/LICENSE). Fork it.

**Comment by ryanvanderpol** [comment]
+1

@bvaughn cause we're lazy and want to use the existing npm package instead of creating a whole new set of dependencies to maintain and potentially have to switch back later on.

**Comment by fungilation** [comment]
A lingering warning still on RN 0.47.1:
```
ExceptionsManager.js:73 Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
reactConsoleErrorHandler @ ExceptionsManager.js:73
printWarning @ warning.js:35
warning @ warning.js:59
get @ react.development.js:2133
(anonymous) @ index.js:101
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ index.js:1
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ components.js:30
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ index.ios.js:88
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:119
_require @ require.js:110
(anonymous) @ redux-logger.js:1
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:65
```
```
ExceptionsManager.js:73 Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
reactConsoleErrorHandler @ ExceptionsManager.js:73
printWarning @ warning.js:35
warning @ warning.js:59
get @ react.development.js:2125
(anonymous) @ ToolTip.ios.js:24
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ components.js:53
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:126
_require @ require.js:110
(anonymous) @ index.ios.js:88
loadModuleImplementation @ require.js:174
guardedLoadModule @ require.js:119
_require @ require.js:110
(anonymous) @ redux-logger.js:1
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:65
20:13:15.465 
```

Unless you are telling me you can't reproduce these warnings in any RN >= 0.45 project?
screenshot 2017-08-03 20 21 15

**Comment by mrdezzods** [comment]
Sorry for the trouble guys. I will be maintaining this package from now on. 

This issue has been resolved with #483

**Comment by adrienthiery** [comment]
Thanks @mrdezzods ! 👏

**Comment by fungilation** [comment]
Hurray this package is alive again! Some nice PRs pending ;)

**Pull request closed without merging**
