### PR TITLE
fix deprecated scrollTo and fix android next-prev buttons

### LINKED ISSUE #95: scrollTo method changed in React Native 0.20.0
`scrollTo(y, x, animated)` is deprecated. Use `scrollTo({x: 5, y: 5, animated: true})` instead.

### PR DESCRIPTION
**Pull request by FaridSafi**
Thanks for this component
fix #95 #106 #79

### CODE REVIEW

**Comment by FaridSafi** [comment]
loop={true} is not working in Android
My fixes are to use with loop={false} in Android

**Comment by magrinj** [comment]
+1 need to be merge!

**Comment by tonylinyy** [comment]
hope to be merge,thanks

**Comment by abhaytalreja** [comment]
@rajkissu - I see the depricated warning i am running on v1.4.3 `"react-native-swiper": "^1.4.3",` #106  #107 #118

**Comment by rajkissu** [comment]
@abhaytalreja the latest merge has not been published on npm, waiting on @leecade to sort that out. You may install from the github repo directly for the time being.

**Pull request merged**
