### PR TITLE
Loading Minimal is not working on Android when hidden views instantia…

### PR DESCRIPTION
**Pull request by opolyo01**
…ted with Animated.View or ActivityIndicator

### CODE REVIEW

**Comment by rpopovici** [comment]
this fix works for RN 0.43

**Comment by arribbar** [comment]
It works fine for me.

**Comment by arribbar** [comment]
It works well in my app. Thank you!

**Comment by arribbar** [comment]
Someone can accept this PR, please ?

**Comment by manuelkch** [comment]
Works on RN 0.37 to. Can someone merge this PR ?

**Comment by Kris4an7** [comment]
Sorry for the probably stupid question, but how do I use this ? Do I have to change the files by myself or ? Already a few times I found a solution to a problem I am having by someone creating a separate branch, but I have no idea how to apply the fixed in this branch to my react-native project. 

Thank you !

**Comment by AlexDM0** [comment]
We'd also be interested in this fix!

**Comment by arribbar** [comment]
It should be working now with version 1.5.9. @opolyo01, can you try if you have still the bug with le last version ?
To answer your question @Kris4an7, you can add a github project, tag or branch in your package.json instead of a version number.

**Comment by arribbar** [comment]
Feel free to reopen this PR if needed, resolving conflicts at the same time

**Pull request closed without merging**
