### PR TITLE
added scrollTo

### PR DESCRIPTION
**Pull request by alattanzio**
### Is it a bugfix ?
- No ?

### Is it a new feature ?
- Yes
- scrollTo specific slider

### Describe what you've done:
scroll to specific slider

### How to test it ?
call scrollTo using a button, and swiper reference, using index as parameter (eg, using a toolbar on top)

### CODE REVIEW

**Comment by ue** [comment]
Merge It !

**Comment by danikane** [comment]
Please merge. 😃

**Comment by acollazomayer** [comment]
Merge it!!

**Comment by danikane** [comment]
this.refs.swiper.scrollBy(index - this.state.index) works around this for me btw.
A scrollTo index would still be better though. :)

**Comment by thiswayq** [comment]
👍 Can we have this? the above solution works but scrollTo would be very nice.

**Comment by ManigandanRaamanathan** [comment]
@leecade please merge this. ScrollTo is very important compared to ScrollBy

**Comment by alattanzio** [comment]
I don't have write access. sorry

**Comment by tobiascornille** [comment]
Shouldn't this also be added to the typescript definition like #931?

**Comment by edoantonioco** [comment]
how is this meant to be used? I dont see any scrollTo property in latest nightly version

**Comment by sintylapse** [comment]
Doesn't seems to be working

**Pull request merged**
