### PR TITLE
Improve the way to override controls buttons (nextButton & prevButton)

### PR DESCRIPTION
**Pull request by tsunammis**
Hello,

Currently it is complicated to override easily controls (nextButton & prevButton).

If the looping is disable, we have to know the state of index, so, I suggest an improvement to avoid the knowing of state.index to override controls (nextButton and prevButton).

I updated the README accordingly my PR.

Best,

### CODE REVIEW

**Comment by tsunammis** [comment]
@leecade What do you think about this PR ?

**Comment by leecade** [comment]
Looks great! thanks @tsunammis, I will release it soon

**Comment by tsunammis** [comment]
@leecade Thanks, I'm looking forward to see it merged, like that I could use it on my project instead of my fork ;-)

**Comment by tsunammis** [comment]
@leecade Thank you!

**Comment by tsunammis** [comment]
@leecade Could you create a new tag related to this improvement ?

**Comment by jchonde** [comment]
Hi, I badly need to customize my buttons. Could you publish onto npm those modifications please ?

**Comment by tsunammis** [comment]
@leecade any news ?

**Comment by tsunammis** [comment]
@leecade any news ?

**Comment by tsunammis** [comment]
@leecade Are you alive ?

**Comment by grabbou** [comment]
^ it doesn't work actually, so not sure if publishing will change anything, huh.

**Comment by tsunammis** [comment]
@grabbou The merge request has been merged with the master, so, If I configure my package.json on the master of this repo, it works, but, it is more logical to set a specific version than the master branche ;-)

**Comment by grabbou** [comment]
It's quite interesting since two commits pushed between your merge are the ones that produce errors. Anyway, if you want to keep contributing in the meantime, feel free to visit my fork. Hopefully I'll manage to submit a release with refactored code soon.

**Comment by tsunammis** [comment]
Ok, so, I can switch to your fork, this is not a problem. But, I didn't see it in your repository list -> https://github.com/grabbou?tab=repositories

Moreover, did you integrated my PR ?

**Comment by grabbou** [comment]
Yep, it's there. It's actually https://github.com/manandmoon/react-native-swiper and I guess release 2.0.0 is the one you are looking for. I am currently trying to update it & clean it up + resolve some other issues as well. Haven't tested newer releases yet.

**Pull request merged**
