### PR TITLE
It is now possible to listen to index changes when user swipes

### LINKED ISSUE #436: Can I get current index when the user swiped?
I want keep the state of my slider synced in Redux, therefore I need to know when the user swiped.

Is that possible?

### PR DESCRIPTION
**Pull request by brendan-rius**
There is now a simple way to listen to user's swipes.

I added a method `onIndexChanged` that is called with the new index everytime the user swipes. This allows, for example, to link this component to a Redux store.

Fixes #436

### CODE REVIEW

**Comment by bennygenel** [comment]
Hi @brendan-rius;
I tried the changed but after the change dots stopped working. Why do you think it happened?
Thanks

**Comment by brendan-rius** [comment]
Can you give me your code sample please so I can try to reproduce the bug locally?

**Comment by bennygenel** [comment]
Its pretty basic usage I suppose.

```
onIndexChanged(index){
  console.log('Swiper Index: ', index);
}

render(){
  return(
  <Swiper style={styles.wrapper} showsButtons={true}
        loop={false}
        height={this.props.height}
        width={this.props.width}
        activeDot={<View style={styles.activeDot} />}
        dot={<View style={styles.dot} />}
        nextButton={<Text style={styles.nextPrevButton}></Text>}
        prevButton={<Text style={styles.nextPrevButton}></Text>}
        onIndexChanged={this.onIndexChanged.bind(this)}
      >
        <View style={styles.slide1}>
            <Text style={styles.text}>{'slide1Line1'}</Text>
        </View>
        <View style={styles.slide2}>
          <Text style={styles.text}>{'slide2Line2'}</Text>
        </View>
        <View style={styles.slide3}>
          <Text style={styles.text}>{'slide3Line3'}</Text>
        </View>
        <View style={styles.slide4}>
          <Text style={styles.text}>{'slide4Line4'}</Text>
        </View>
      </Swiper>
  )
}
```

**Comment by brendan-rius** [comment]
There was actually a tiny bug. I thing it should work better now. Does it?

**Comment by bennygenel** [comment]
Yes. I can confirm that my code is working.
Thanks for the quick update.

**Comment by brendan-rius** [comment]
Thank you for testing :)

**Comment by JavRok** [comment]
Please please, merge this pull request. I need this functionality :)

**Comment by danieltr10** [comment]
Merge please :)

**Comment by malimichael** [comment]
I think it would be worth noting that it has always been possible to listen to index changes through the `onMomentumScrollEnd` prop you can pass directly to the Swiper.

```
class MySwiper extends Component {
  onScrollEnd = (e, state) => {
    console.log('Index is:', state.index);
  };

  render() {
    return (
      <Swiper onMomentumScrollEnd={this.onScrollEnd}>
        <View style={styles.slide1}>
          <Text style={styles.text}>View 1</Text>
        </View>
        <View style={styles.slide2}>
          <Text style={styles.text}>View 2</Text>
        </View>
        <View style={styles.slide3}>
          <Text style={styles.text}>View 3</Text>
        </View>
      </Swiper>
    );
  }
}
```

**Comment by mateofd** [comment]
Thanks @malimichael for your solution! It works like a charm. Perhaps instead of messing with the code proposed in this branch they should put that in the documentation.

**Comment by mrdezzods** [comment]
Will update npm today

**Pull request merged**
