### PR TITLE
Fix/android swiper

### PR DESCRIPTION
**Pull request by msutariya**

### CODE REVIEW

**Review by booleanBoy — COMMENTED** [review]
Solve the problem of the Swiper not rendering the content while within a Modal for me on Android.

**Comment by StefanYohansson** [comment]
Solve the problem to load react-native-swiper (1.5.13) with react-navigation.

**Review by StefanYohansson — COMMENTED** [review]
Solve the problem to load react-native-swiper (1.5.13) with react-navigation.

**Comment by JackHowa** [comment]
is this a priority to have it work on Android? I'm looking at some issues #446 that reference this pr

**Comment by sarmadsaleem** [comment]
Are there any plans to merge this PR in near future?

**Comment by hugohow** [comment]
+1

**Comment by TheryFouchter** [comment]
Thanks, fixed issues #435

**Review by ghost — CHANGES_REQUESTED** [review]
This change broke button onPress on control buttons, the fix is in index.js (function scrollBy) from line 464 to 468: you have to delete platform specific condition an only leave:

this.scrollView && this.scrollView.scrollTo({ x, y, animated })

**Comment by Patzelly** [comment]
Thanks it's working

**Pull request closed without merging**
