### PR TITLE
fixes deprecated native scrollTo call

### PR DESCRIPTION
**Pull request by joeferraro**

### CODE REVIEW

**Comment by teejayvanslyke** [comment]
+1

**Comment by jnak** [comment]
+1 it should be ready to be merged. thx

**Comment by mcnamee** [comment]
+1 I've tested and this removes the deprecated warnings. Please merge

**Comment by jevakallio** [comment]
+1 @leecade can you please merge this and publish to NPM. Currently this blocks using `react-native-swiper` with React Native 0.20 and beyond, and we are forced to depend on a fork.

**Comment by bluesky0109** [comment]
+1

**Comment by naeemulhaque** [comment]
+1

**Comment by nicole1314** [comment]
@jevakallio I'm experiencing exactly the same using Swiper.

**Comment by artem-russkikh** [comment]
+1

**Comment by rajkissu** [comment]
I'm closing this as it has been resolved in pull request #112

**Pull request closed without merging**
