### PR TITLE
Added scrollBy method into the types definition file

### PR DESCRIPTION
**Pull request by svbutko**
### Is it a bugfix ?
- No
### Is it a new feature ?
- No
### Describe what you've done:
- Added scrollBy method into the types definition file

### CODE REVIEW

**Comment by superdopey** [comment]
Shouldn't this be added to the SwiperProps interface?

**Comment by betko** [comment]
Hi! Any plan to merge this?

**Comment by dfalling** [comment]
I'd love to see this get in.  The workarounds are not ideal.

**Comment by ArrayZoneYour** [comment]
Duplicate of #1000

**Pull request closed without merging**
