### PR TITLE
Optionally disable the 'next' control button

### PR DESCRIPTION
**Pull request by SSTPIERRE2**
Relates to issue: https://github.com/leecade/react-native-swiper/issues/530

If something is off or I missed anything  just let me know, thanks!

### CODE REVIEW

**Comment by SSTPIERRE2** [comment]
I have tested this, by the way, it works nicely!

**Comment by arribbar** [comment]
Thanks @SSTPIERRE2 
I'll take a look on monday if no one has done it yet.
If you want to do it faster, you could create a quick example with the list to test your new feature.

**Comment by SSTPIERRE2** [comment]
Hehe thank you very much!

**Comment by SSTPIERRE2** [comment]
@arribbar Quick question does this change make it into master right away? Or is there maybe a release schedule that this gets added to?

**Comment by arribbar** [comment]
A new release will be made today.

**Comment by SSTPIERRE2** [comment]
That's so cool, I figured by looking at the branches. Really well organized project!

**Comment by yaraht17** [comment]
I using version 1.5.12, but it not working 
screen shot 2017-09-21 at 18 44 15

**Comment by SSTPIERRE2** [comment]
@arribbar I tried installing the latest version but I don't seem to see my change, am I missing something? Thanks!

**Comment by SSTPIERRE2** [comment]
@arribbar @leecade  should I just fork the project and make my change? I don't see it having made it to master. Thanks!

**Comment by arribbar** [comment]
Weird, I might have made a mistake. I'll publish a new version on Monday
Sorry...

**Comment by SSTPIERRE2** [comment]
@arribbar Hey no problem, thanks for your time! Much appreciated.

**Comment by HoangTran1601** [comment]
How about disable prev button ?

**Comment by Csear007** [comment]
@HoangTran1601 I just created a new pull request (#749)  to disable prev button

**Pull request merged**
