### PR TITLE
button color change through props

### PR DESCRIPTION
**Pull request by ravingupta**
Anyone can change button colors

### CODE REVIEW

**Comment by fxhereng** [comment]
Can this PR be integrated in master?

I would prefer not to have to clone the component into my project, this lib is pretty nice.

I would appreciate, thanks!

**Comment by ravingupta** [comment]
Yes, you can integrate this without any conflicts...

**Comment by arribbar** [comment]
Feel free to reopen this PR if needed, resolving conflicts at the same time. I would take a look then

**Comment by manjeets12** [comment]
@ravingupta  @arribbar I think it would be better to use style prop instead of string for color, that way we can have more freedom, see below
in propTypes we can have 
`buttonTextStyle:PropTypes.oneOfType([PropTypes.object, PropTypes.number]),`
in defaultProps we can have
`buttonTextStyle:PropTypes.oneOfType([PropTypes.object, PropTypes.number]),`

within renderNextButton and renderPrevButton we can have 
```
renderNextButton = () => {
    let button = null

    if (this.props.loop ||
      this.state.index !== this.state.total - 1) {
      button = this.props.nextButton || <Text style={[styles.buttonText, this.props.buttonTextStyle]}>›</Text>
    }

    return (
      <TouchableOpacity
        onPress={() => button !== null && this.scrollBy(1)}
        disabled={this.props.disableNextButton}
      >
        <View>
          {button}
        </View>
      </TouchableOpacity>
    )
  }
```

we can use this in following manner

 ```
<Swiper
                    style={styles.wrapper}
                    showsButtons={true}
                    buttonTextStyle={{color:'#9e9e9e', fontSize:24}}
                    showsPagination={false}
                    loadMinimal={true}
                    loadMinimalSize={2}
                    ref='listView'>
                    {Your_VIEWS_TO_RENDER}
                </Swiper>
```

**Pull request closed without merging**
