### PR TITLE
New Features: Background Image and Header

### PR DESCRIPTION
**Pull request by charlle**
I added 2 features, which may be useful to others.
1. You can simply pass in a custom component as a Header to your Swiper
2. You can add a background image to your swiper
The README docs were updated with the new properties and an example was included in /examples/components/Header/
Let me know if you catch anything.

Enjoy!

### CODE REVIEW

**Comment by arribbar** [comment]
Feel free to reopen this PR if needed, resolving conflicts at the same time. I would take a look at this PR then :)

**Comment by charlle** [comment]
@arribbar did you see conflicts somewhere?

**Comment by arribbar** [comment]
Sorry, I do some cleaning. I can check it later and merge it if you need it. Just reopen it and I'll do it

**Comment by charlle** [comment]
@arribbar I will re open, thanks.

**Pull request closed without merging**
