### PR TITLE
Move Dimensions import to deconstructed imprt for react-native 0.14+

### PR DESCRIPTION
**Pull request by jedrekk**

### CODE REVIEW

**Comment by stereodenis** [comment]
Need this

**Comment by guzijiang** [comment]
I modified code,but the problem still exist.QAQ

**Comment by wenkangzhou** [comment]
Thanks,it works.

**Comment by udnaan** [comment]
+1

Make sure that you do an npm start inside the  package if you manually modify the src/index.js

**Comment by andresn** [comment]
@leecade can we get a merge please?

**Comment by andresn** [comment]
@leecade thank you and nice component btw!

**Pull request merged**
