### PR TITLE
Add react-timer-mixin as dependency

### LINKED ISSUE #28: please list react-native-timer-mixin as a dep

### PR DESCRIPTION
**Pull request by insanehunter**
This PR fixes #28

### CODE REVIEW

**Comment by wenzhixin** [comment]
:+1:

**Comment by brunoguerra** [comment]
:+1: please merge this pull request!

**Comment by rreusser** [comment]
I don't want to be too hasty in assuming it's abandoned (and with no lack of gratitude for what's a pretty great and easy-to-use module), but you might try submitting this to https://github.com/manandmoon/react-native-swiper After a couple months, maybe it's time to fork and get some PRs merged.

**Comment by leecade** [comment]
fixed by #64, sorry for so later

**Comment by rreusser** [comment]
No worries! I know. It's hard to stay on top of lots of modules and bug fixes. I appreciate your work though!

**Pull request closed without merging**
