### PR TITLE
Change ViewPagerAndroid to ViewPager from @react-native-community/vie…

### PR DESCRIPTION
**Pull request by grean**
Replacing ViewPagerAndroid component by @react-native-community/viewpager
### Is it a bugfix ?
No
### Is it a new feature ?
No
### Describe what you've done:
Replacing ViewPagerAndroid component because this module will be removed from react-native Core libraries.
### How to test it ?
Install this package @react-native-community/viewpager according to the documentation and link it to your project.
Then compile you project.
It would work.

### CODE REVIEW

**Comment by retyui** [comment]
This repo dead: https://github.com/leecade/react-native-swiper/issues/713
Your issue is like other 480+ issues, will not be resolved in the short term.

**Comment by hqarymkevich** [comment]
what is going with this issue? When would it  be changed?

**Comment by grean** [comment]
idk but i'have made my own fork and i point to it in my package.json for my needs.
"react-native-swiper": "git+https://git@github.com/grean/react-native-swiper.git",
So for the moment i'm fine.

**Comment by ArrayZoneYour** [comment]
@grean Thanks for contribution, ViewPagerAndroid has been migrated to @react-native-community/viewpager in #997

**Pull request closed without merging**
