### PR TITLE
Changed ScrollBy for directly animation with Index

### PR DESCRIPTION
**Pull request by peacecwz**

### CODE REVIEW

**Comment by arribbar** [comment]
Thanks @peacecwz for your PR.
Can you describe what you intend to do and how to test it, please ?
Also, you might want to update your index file.

**Comment by arribbar** [comment]
@peacecwz With no more info, I'll close the PR.

**Comment by peacecwz** [comment]
I'm sorry for late. We have used it on our project. I tested it on iOS and Android. You can look it on our app https://play.google.com/store/apps/details?id=com.CodeFiti.Scode.

When you used 'scrollBy' function, it increments index with parameter
This PR is about navigation between swiper items with index
Before PR

Example
Swiper Current Index is 2 and run " this.refs.swiper.scrollBy(1)" then index will be 3

After PR

Example
Swiper Current Index is 2 and run "this.refs.swiper.scrollBy(1,true,true)" then index will be 1

**Comment by ArrayZoneYour** [comment]
add scrollTo in #831

**Pull request closed without merging**
