### PR TITLE
Dimensions is now included in react-native

### LINKED ISSUE #31: Unable to resolve module Dimensions from
Hello,

I get the following warning in the packager:
````javascript
Unable to resolve module Dimensions from .... dist.js
````

Any idea how to fix that? Everything is working correctly, just the message in the packager.

Regards

### PR DESCRIPTION
**Pull request by ldesplat**
Fixes #31

### CODE REVIEW

**Comment by wenzhixin** [comment]
:+1:

**Comment by kyle-ssg** [comment]
Can this please be merged in ? :+1:

**Comment by dabeeeenster** [comment]
+1!

**Comment by fishedee** [comment]
+1!

**Comment by smothers** [comment]
:+1:

**Comment by barakcoh** [comment]
+1

**Comment by benaneesh** [comment]
:+1:

**Comment by benaneesh** [comment]
Fixed another Dimensions bug #56

**Comment by leecade** [comment]
fixed by #64, sorry for so later

**Pull request closed without merging**
